name: Run the linters and detect if a secret has leaked

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check_pr_name:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get yarn cache directory path
      uses: c-hive/gha-yarn-cache@v2
    - name: Install dependencies
      run: yarn install
    - name: Install Dependencies
      run: |
        yarn add commitlint-config-gitmoji commitlint 
        echo "module.exports = {extends: ['gitmoji']};" > ./commitlint.config.js
    - name: Run PR name linter
      uses: JulienKode/pull-request-name-linter-action@v0.5.0

  run_precommit_hooks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2

    - name: Get yarn cache directory path
      uses: c-hive/gha-yarn-cache@v2

    - name: Install dependencies
      run: yarn install

    - name: Run pre-commit hooks
      uses: pre-commit/action@v2.0.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        SKIP: markdownlint-fix

